language: java
sudo: false
jdk:
  - openjdk8
  - openjdk11

script: mvn clean install -Dmaven.repo.local=$HOME/.m2/repository

addons:
  sonarcloud:
    organization: "wiiitek-github"
    token:
      secure: 'kIEVqkkPToOM2unHC326AIwPuvoDVbgQzcmVTy3hihZSNfMqdCXPThgfuvfQogsjbkP3/YkpOr9P/EH17JiySSySUrK1HgHBOpi94Y55xfE5W3QYbcTNIa8f5wNkae+hDM4GmtmVu6MIdbqfTkrru1mFQRyM6MUmlL9B98bP8mbUCDRt50ly22TiLcTVe56QEr2pvwb7Iy1/ynkouzRjv436g1DWeCjDrmfwRHkUUWyMjfWhRornivp7DHBnZiMlHb/zXwfMvD0BdauFp+pZw2WleuNA444mQiJr38XV9/0xfCSlS8GHg6RKhMlQpK6leT26QL83cLWIc0qkvph6viGP7rKV4IYjCk6Ea9qjKptnaHnZ8a0+PtmvjooPodE05mNzbs7KmeiXayllLvrN20ZyeXQi7LQL4XwzZnlQJaI1wXr3+/rC/elr7s5I8AYbLGamPGNQt4A7qXQgpoP/R5AbkwUCrtwEQiQBrbIrXeB8S7U7VdR42A2TXO8R1p+8RrwhuUxC4p+5XHQ4SZ+KeUwhdsuicjQ0zgvOLlvB6/QyAy0ls3IWsLLpoBwmN4osyk6taEVR6jiL8uovjCXYQeUfZX5Vspi6Ptgt1HgYFavDjn8I6Gd5X6Nr216Omvc7kSn1TbZL0R0Y+zwsRGjdroNS4YomSglhbCQHVVVjx6M='

# see
# https://docs.travis-ci.com/user/build-stages#Build-Stages-and-Build-Matrix-Expansion
jobs:
  include:
    - stage: sonar
      jdk: openjdk11
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report -Dmaven.repo.local=$HOME/.m2/repository
        - mvn sonar:sonar -Dsonar.projectKey=pl.kubiczak:jade-to-filters-maven-plugin -Dsonar.projectKey=wiiitek_pl.kubiczak.felix.shark.samples
