language: java
sudo: false
jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "wiiitek-github"
    token:
      secure: JF5pFnDiXM3ySW8afQupNL2QP4N7ymI+BUYC4Q++1qfvp1kI+/sO0ew3qqL8MPvVjRl3+FLx+/3XNZL3yUkBPjvS9Dmrb0XG+cEWXTrgunzHpgARTBw58l7vZvos1ry0BCWZwrFV3NZROlSEqzWl1CYsKPHxWP3/f9QN+9+1gMXN8s7PUAEEQZhAOXPGHKodaDE5moeA0LgFUfn/5zNhiagruBS/Xukwhe3RVRROyIassSHxAzAjTqWCnKQLlhFOQQGOi40BvMh0TlPdNHY7Mx3Z8yenlav3/Xkw3frKsXey8qfgM2sjjr/7VsArw+unZ+Qq4tniKcOdRHMsdVTbefozYGqVj5EGHxRSiFzERS6dbUYZ7H390ND36UsOsWsWUBGRnXOJDpyq765GPCIInPDwAETpoSVTqV4tXRs8KGUMfQFYhUNcoyjrXdxHV7PKZxm71Al6CB+++UxgrGOihyBCYQ5sqOLDgzKJCBTyHGZubBHBm3p2HvkvmIf7Go38O3BmWcKqaXhUku0IfadmQBeVnPi8LEJ6eluTbvmH3jDOPNqkRXv7KYOcNBTVtNrOZ/g0mLLo19VY6iPykJBe5V+ewK9nU9Lgod/XtR55bc9y2APUscL84TQZ0h3chTx5LJSX7Q9LonQB1FWnC4RBtzX8zrV6ZIph+4zhrfGUngk=

# see
# https://docs.travis-ci.com/user/build-stages#Build-Stages-and-Build-Matrix-Expansion
jobs:
  include:
    - stage: sonar
      jdk: openjdk11
      script: mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dmaven.repo.local=$HOME/.m2/repository
